config_env: &defaults
  working_directory: ~/code
  environment:
    JVM_OPTS: -Xmx3200m
    #GRADLE_OPTS: -Xmx512m
config_cache: &config_cache
  key: jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
config_cache_restore: &config_cache_restore
  <<: *config_cache
  keys:
    - jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-
    - jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-
config_cache_save: &config_cache_save
  <<: *config_cache
  #when: always
  paths:
    - ~/.gradle
    #- ~/.gradle/wrapper/dists
    #- ~/.gradle/cache/modules-2
    - ~/.m2
    #- $ANDROID_HOME/build-tools/27.0.2
config_test_api: &config_test_api
  <<: *defaults
  steps:
    - run:
        name: Correction android environment
        command: sdkmanager "build-tools;27.0.2"
    - attach_workspace:
        at: ..
    - restore_cache:
        <<: *config_cache
    - restore_cache:
        #key: android-img-{{ checksum .cicleci/config.yml }}
        key: android-img-test
    - run:
        name: debug env
        command: |
            pwd
            uname -a
            uname -m
            lsb_release -a
            emulator -version
    - run:
        name: Setup emulator
        command: |
            sdkmanager --update
            ARCH=$(uname -m)
            sdkmanager "system-images;android-${API};google_apis;${ARCH}"
            if [ $? -ne 0 ] && [ "$ARCH" = "x86_64" ]; then sdkmanager "system-images;android-${API};google_apis;x86"; ARCH='x86'; fi
            echo "no" | avdmanager create avd -n test -k "system-images;android-${API};google_apis;${ARCH}"
            echo "Emulator's exit code is $?"
    - save_cache:
        key: android-img-test
        paths:
          #- ${ANDROID_HOME}/system-images
          - /opt/android/sdk/system-images
    - run:
        name: Launch emulator
        background: true
        command: |
            ARCH=$(uname -m)
            export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib
            #ERROR: x86(_64) emulation currently requires hardware acceleration!
            if [ "$ARCH" = "x86" ] || [ "$ARCH" = "x86_64" ]; then EMU="emulator64-x86 -accel off"; else EMU="emulator64-arm -accel on"; fi
            echo "Use $EMU in $ARCH environment"
            $EMU -avd test -noaudio -no-boot-anim -no-window
    - run:
        name: Wait emulator start
        command: |
            circle-android wait-for-boot
            sleep 30
            adb shell input keyevent 82
    - run:
        name: Run tests on emulator
        command: ./gradlew connectedAndroidTest
    - store_artifacts:
        path: app/build/reports
        destination: reports
    - store_test_results:
        path: app/build/outputs/androidTest-results
    - store_artifacts:
        path: app/build/outputs/androidTest-results
        destination: androidTest-results

version: 2
jobs:
  build_and_check:
    <<: *defaults
    docker:
      - image: circleci/android:api-25-alpha
    #branche:
    #  ignore:
    #    - /feature/*
    steps:
      - run:
          name: Correction android environment
          command: sdkmanager "build-tools;27.0.2"
      - checkout
      - restore_cache:
          <<: *config_cache_restore
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          <<: *config_cache_save
      - run:
          name: Run Tests
          command: ./gradlew check lint
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Build Debug APK
          command: ./gradlew assemble
      - store_artifacts:
          #path: build/apk
          #path: app/build/apk
          path: app/build/outputs/apk
          destination: build
      - persist_to_workspace:
          root: ..
          paths:
            - code

  test:
    <<: *defaults
    docker:
      - image: circleci/android:api-25-alpha
    #branche:
    #  ignore:
    #    - /feature/*
    steps:
      - run:
          name: Correction android environment
          command: sdkmanager "build-tools;27.0.2"
      - attach_workspace:
          at: ..
      - restore_cache:
          <<: *config_cache_restore
      - run:
          name: Run Tests
          command: ./gradlew test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/test-results
          destination: test-results
      - save_cache:
          <<: *config_cache_save

  test_api_23:
    <<: *config_test_api
    environment:
      API: 23
    docker:
      - image: circleci/android:api-23-alpha

  test_api_24:
    <<: *config_test_api
    environment:
      API: 24
    docker:
      - image: circleci/android:api-24-alpha

  test_api_25:
    <<: *config_test_api
    environment:
      API: 25
      #IMG_ARCH: armeabi-v7a
    docker:
      - image: circleci/android:api-25-alpha

  test_api_26:
    <<: *config_test_api
    environment:
      API: 26
      #IMG_ARCH: x86_64
    docker:
      - image: circleci/android:api-26-alpha

  test_api_27:
    <<: *config_test_api
    environment:
      API: 27
      #IMG_ARCH: x86
    docker:
      - image: circleci/android:api-27-alpha

workflows:
  version: 2
  build_check_test:
    jobs:
      - build_and_check
      - test:
          requires:
            - build_and_check
      - tests_api:
          requires:
            - test
          filters:
            branches:
              only:
                #- master
                #- develop
                #- hotfix.*
                - disabled
      - test_api_23:
          requires:
            - tests_api
      - test_api_24:
          requires:
            - tests_api
      - test_api_25:
          requires:
            - tests_api
      - test_api_26:
          requires:
            - tests_api
      - test_api_27:
          requires:
            - tests_api
#- deploy_debug:
#    requires:
#      - build
#      - test
#      - test_api
#    filters:
#      branches:
#        only: develop
#- deploy:
#    requires:
#      - build
#      - test
#      - test_api
#    filters:
#      branches:
#        only:
#          - master
#          - hotfix.*
