defaults: &defaults
  working_directory: ~/code
  environment:
    JVM_OPTS: -Xmx3200m
    #GRADLE_OPTS: -Xmx512m
config_cache: &config_cache
  key: jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
config_cache_restore: &config_cache_restore
  <<: *config_cache
  keys:
    - jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-
    - jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-
config_cache_save: &config_cache_save
  <<: *config_cache
  #when: always
  paths:
    - ~/.gradle
    #- ~/.gradle/wrapper/dists
    #- ~/.gradle/cache/modules-2
    - ~/.m2
    #- $ANDROID_HOME/build-tools/27.0.2

version: 2
jobs:
  build_and_check:
    <<: *defaults
    docker:
      - image: circleci/android:api-25-alpha
    #branche:
    #  ignore:
    #    - /feature/*
    steps:
      - run:
          name: Correction android environment
          command: sdkmanager "build-tools;27.0.2"
      - checkout
      - restore_cache:
          <<: *config_cache_restore
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          <<: *config_cache_save
      - run:
          name: Run Tests
          command: ./gradlew lint
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Build Debug APK
          command: ./gradlew assemble
      - store_artifacts:
          #path: build/apk
          #path: app/build/apk
          path: app/build/outputs/apk
          destination: build
      - persist_to_workspace:
          root: ..
          paths:
            - code

  test:
    <<: *defaults
    docker:
      - image: circleci/android:api-25-alpha
    #branche:
    #  ignore:
    #    - /feature/*
    steps:
      - run:
          name: Correction android environment
          command: sdkmanager "build-tools;27.0.2"
      - attach_workspace:
          at: ..
      - restore_cache:
          <<: *config_cache_restore
      - run:
          name: Run Tests
          command: ./gradlew test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/test-results
          destination: test-results
      - save_cache:
          <<: *config_cache_save

workflows:
  version: 2
  build_check_test:
    jobs:
      - build_and_check
      - test:
          requires:
            - build_and_check
